apiVersion: v1
kind: ConfigMap
metadata:
  name: vega-config
  namespace: vega
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "vega-app"
  Jwt_Audience: "vega-users"
  Jwt_ExpiresMinutes: "60"
  Services__CartUrl: "http://cart-service:8080"
  Services__PaymentUrl: "http://payment-service:8080"
  Services__ProductUrl: "http://product-service:8080"
